-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. Poems Table (Mixed: Public Classics + Private Letters)
create table public.poems (
  id bigint generated by default as identity primary key,
  title text not null,
  content text not null,
  author text default 'Unknown',
  
  -- Sender/Receiver Logic
  is_public boolean default true,
  sender_user_id uuid references auth.users(id),
  target_email text, -- Simple way to link to partner without complex ID exchange for MVP
  
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Profiles (One row per user)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  last_opened_date date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Unlocked Poems (History)
create table public.unlocked_poems (
  id bigint generated by default as identity primary key,
  user_id uuid references public.profiles(id) not null,
  poem_id bigint references public.poems(id) not null,
  unlocked_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, poem_id)
);

-- RLS

alter table public.poems enable row level security;
alter table public.profiles enable row level security;
alter table public.unlocked_poems enable row level security;

-- Policies

-- Poems:
-- 1. Public poems are visible to everyone.
-- 2. Private poems are visible ONLY to the sender ID OR the target_email (if user email matches).
create policy "View poems logic"
  on public.poems for select
  using (
    is_public = true 
    or sender_user_id = auth.uid()
    or target_email = (select email from auth.users where id = auth.uid()) -- Note: this requires a way to read auth.users email or store it in profiles
  );

-- Simplified Policy for MVP (relying on client filtering or profiles table email)
-- Let's rely on profiles table having the email sync'd.
create policy "View poems via profile"
  on public.poems for select
  using (
    is_public = true 
    or sender_user_id = auth.uid()
    or target_email in (select email from public.profiles where id = auth.uid())
  );

create policy "Users can insert custom poems"
  on public.poems for insert
  with check ( auth.uid() = sender_user_id );

-- Profiles:
create policy "Users can view own profile" on public.profiles for select using (auth.uid() = id);
create policy "Users can update own profile" on public.profiles for update using (auth.uid() = id);
create policy "Users can insert own profile" on public.profiles for insert with check (auth.uid() = id);

-- Unlocks:
create policy "Users can view own unlocks" on public.unlocked_poems for select using (auth.uid() = user_id);
create policy "Users can insert own unlocks" on public.unlocked_poems for insert with check (auth.uid() = user_id);
